In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import glob

In [2]:
mf = pd.read_csv(r'D:\Prog\ICRI\climate_change\raw_data\Country-level estimates\v10_cnty.csv')
mf[(mf['iso3'] == 'IRQ') & (mf['age'] == 999) & (mf['edu'] == 999) & (mf['female'] == 999) & (mf['urban'] == 999)]

,superregion2,iso3,age,female,urban,edu,year,v10_type,v10_type_desc,median,lowerci_95,upperci_95,serving,s_lowerci_95,s_upperci_95
833872,MENA,IRQ,999.0,999,999,999,1990,1,1: Foods & Beverages,174.461423,141.732423,202.067816,1.770643,1.438470,2.050825
833873,MENA,IRQ,999.0,999,999,999,1995,1,1: Foods & Beverages,41.847798,29.635444,59.933785,0.424721,0.300776,0.608280
833874,MENA,IRQ,999.0,999,999,999,2000,1,1: Foods & Beverages,36.227765,25.830478,52.044272,0.367683,0.262159,0.528207
833875,MENA,IRQ,999.0,999,999,999,2005,1,1: Foods & Beverages,33.966165,24.066753,48.641213,0.344729,0.244258,0.493669
833876,MENA,IRQ,999.0,999,999,999,2010,1,1: Foods & Beverages,59.977725,42.890112,84.204280,0.608726,0.435300,0.854606
833877,MENA,IRQ,999.0,999,999,999,2015,1,1: Foods & Beverages,61.817481,44.064739,87.682524,0.627398,0.447222,0.889907
833878,MENA,IRQ,999.0,999,999,999,2018,1,1: Foods & Beverages,54.113508,38.455154,77.010528,0.549208,0.390289,0.781595
833879,MENA,IRQ,999.0,999,999,999,2020,1,1: Foods & Beverages,55.414255,39.224606,78.594132,0.562410,0.398098,0.797667

As we can see the unprocessed red meat consumption (median) for Iraq in the year 1990 is much much greater than anything that comes after it. Considering the lower ci and upper ci have the same issue, it seems a mistake was made, but we cannot verify or find the correct value, therefore we opted for removing this entry and the entire 1990 - Iraq records from our analysis.

In [3]:
df = pd.read_csv(r'co2_calc\emissions_v4\Beans_and_legumes_all.csv')
df

     index iso3  year      median  emissions income_group
0        0  AFG  1990   83.317104  63.889055   Low income
1        1  AFG  1995   71.775725  55.038918   Low income
2        2  AFG  2000   42.381433  32.498845   Low income
3        3  AFG  2005   60.322418  46.256316   Low income
4        4  AFG  2010  104.545995  80.167751   Low income
..     ...  ...   ...         ...        ...          ...
149    149  EMR  2000   32.745006  25.109460          NaN
150    150  EMR  2005   34.113871  26.159130          NaN
151    151  EMR  2010   35.919824  27.543967          NaN
152    152  EMR  2015   31.295066  23.997620          NaN
153    153  EMR  2018   37.761307  28.956050          NaN

[154 rows x 6 columns]

In [4]:
df[(df['iso3'] == 'IRQ') & (df['year']==1990)]

    index iso3  year     median  emissions         income_group
42     42  IRQ  1990  48.016401  36.819841  Upper middle income

In [5]:
df.drop(index=df[(df['iso3'] == 'IRQ') & (df['year']==1990)].index, inplace=True)
df['year'].value_counts()

year
1995    22
2000    22
2005    22
2010    22
2015    22
2018    22
1990    21
Name: count, dtype: int64

In [8]:
# def iraq_data_remover(path):
#     glo = glob.glob(os.path.join(path, '*.csv'), recursive=True)
#     n = 0
#     for i in glo:
#         df = pd.read_csv(i)
#         df_cleaned = df.drop(index=df[(df['iso3'] == 'IRQ') & (df['year']==1990)].index)
#         df_cleaned.to_csv(i, index=False)
#         print(f">>> Processed file {n+1}/{len(glo)}: {i}")
#         n += 1 


def iraq_data_remover(path):

    search_path = os.path.join(path, '**', '*.csv')

    files = glob.glob(search_path, recursive=True)

   

    for n, file_path in enumerate(files, 1):

        try:

            df = pd.read_csv(file_path)

           

            target_col = None

            if 'iso3' in df.columns:

                target_col = 'iso3'

            elif 'Country' in df.columns:

                target_col = 'Country'

           

            if target_col and 'year' in df.columns:

                index = (df[target_col] == 'IRQ') & (df['year'] == 1990)



                df_cleaned = df.drop(index=df[index].index)                

                df_cleaned.to_csv(file_path, index=False)

                print(f">>> Processed file {n}/{len(files)}: {file_path}")

            else:

                print(f">>> Skipped file {n}/{len(files)} (Columns missing): {file_path}")



        except Exception as e:

            print(f"Error processing {file_path}: {e}")

In [9]:
iraq_data_remover(r'co2_calc\emissions_v3')

>>> Processed file 1/51: co2_calc\emissions_v3\Beans_and_legumes_all.csv
>>> Processed file 2/51: co2_calc\emissions_v3\Beans_and_legumes_females.csv
>>> Processed file 3/51: co2_calc\emissions_v3\Beans_and_legumes_males.csv
>>> Processed file 4/51: co2_calc\emissions_v3\Cheese_all.csv
>>> Processed file 5/51: co2_calc\emissions_v3\Cheese_females.csv
>>> Processed file 6/51: co2_calc\emissions_v3\Cheese_males.csv
>>> Processed file 7/51: co2_calc\emissions_v3\Eggs_all.csv
>>> Processed file 8/51: co2_calc\emissions_v3\Eggs_females.csv
>>> Processed file 9/51: co2_calc\emissions_v3\Eggs_males.csv
>>> Processed file 10/51: co2_calc\emissions_v3\Fruits_all.csv
>>> Processed file 11/51: co2_calc\emissions_v3\Fruits_females.csv
>>> Processed file 12/51: co2_calc\emissions_v3\Fruits_males.csv
>>> Processed file 13/51: co2_calc\emissions_v3\Fruit_juices_all.csv
>>> Processed file 14/51: co2_calc\emissions_v3\Fruit_juices_females.csv
>>> Processed file 15/51: co2_calc\emissions_v3\Fruit_juices_males.csv
>>> Processed file 16/51: co2_calc\emissions_v3\Milk_all.csv
>>> Processed file 17/51: co2_calc\emissions_v3\Milk_females.csv
>>> Processed file 18/51: co2_calc\emissions_v3\Milk_males.csv
>>> Processed file 19/51: co2_calc\emissions_v3\Non_starchy_vegetables_all.csv
>>> Processed file 20/51: co2_calc\emissions_v3\Non_starchy_vegetables_females.csv
>>> Processed file 21/51: co2_calc\emissions_v3\Non_starchy_vegetables_males.csv
>>> Processed file 22/51: co2_calc\emissions_v3\Nuts_all.csv
>>> Processed file 23/51: co2_calc\emissions_v3\Nuts_females.csv
>>> Processed file 24/51: co2_calc\emissions_v3\Nuts_males.csv
>>> Processed file 25/51: co2_calc\emissions_v3\Other_starchy_vegetables_all.csv
>>> Processed file 26/51: co2_calc\emissions_v3\Other_starchy_vegetables_females.csv
>>> Processed file 27/51: co2_calc\emissions_v3\Other_starchy_vegetables_males.csv
>>> Processed file 28/51: co2_calc\emissions_v3\Potatoes_all.csv
>>> Processed file 29/51: co2_calc\emissions_v3\Potatoes_females.csv
>>> Processed file 30/51: co2_calc\emissions_v3\Potatoes_males.csv
>>> Processed file 31/51: co2_calc\emissions_v3\refined_grains_all.csv
>>> Processed file 32/51: co2_calc\emissions_v3\refined_grains_females.csv
>>> Processed file 33/51: co2_calc\emissions_v3\refined_grains_males.csv
>>> Processed file 34/51: co2_calc\emissions_v3\seafoods_all.csv
>>> Processed file 35/51: co2_calc\emissions_v3\seafoods_females.csv
>>> Processed file 36/51: co2_calc\emissions_v3\seafoods_males.csv
>>> Processed file 37/51: co2_calc\emissions_v3\total_all.csv
>>> Processed file 38/51: co2_calc\emissions_v3\total_females.csv
>>> Processed file 39/51: co2_calc\emissions_v3\total_males.csv
>>> Processed file 40/51: co2_calc\emissions_v3\Total_processed_meats_all.csv
>>> Processed file 41/51: co2_calc\emissions_v3\Total_processed_meats_females.csv
>>> Processed file 42/51: co2_calc\emissions_v3\Total_processed_meats_males.csv
>>> Processed file 43/51: co2_calc\emissions_v3\Unprocessed_red_meats_all.csv
>>> Processed file 44/51: co2_calc\emissions_v3\Unprocessed_red_meats_females.csv
>>> Processed file 45/51: co2_calc\emissions_v3\Unprocessed_red_meats_males.csv
>>> Processed file 46/51: co2_calc\emissions_v3\whole_grains_all.csv
>>> Processed file 47/51: co2_calc\emissions_v3\whole_grains_females.csv
>>> Processed file 48/51: co2_calc\emissions_v3\whole_grains_males.csv
>>> Processed file 49/51: co2_calc\emissions_v3\Yoghurt_all.csv
>>> Processed file 50/51: co2_calc\emissions_v3\Yoghurt_females.csv
>>> Processed file 51/51: co2_calc\emissions_v3\Yoghurt_males.csv